name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run migrations and tests
      env:
        DJANGO_SECRET_KEY: "django-insecure-^wb8f=e)94r&@pomhv4qch-1!@jhax1y^g5a656(@sf&#(z2ki"
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test


