name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Configure Django to use SQLite
      run: |
        echo "DATABASES = {'default': {'ENGINE': 'django.db.backends.sqlite3', 'NAME': ':memory:'}}" > library/settings_ci.py

    - name: Run migrations and tests
      env:
        DJANGO_SETTINGS_MODULE: library.settings_ci
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test library.tests



