name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_DB: livraria_db
          POSTGRES_USER: livraria_user
          POSTGRES_PASSWORD: senha_livraria
        options: >-
          --health-cmd="pg_isready -U livraria_user -d livraria_db"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.4'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h db -p 5432 -U livraria_user; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        echo "PostgreSQL is ready!"

    - name: Run migrations and tests
      env:
        DATABASE_URL: postgres://livraria_user:senha_livraria@db:5432/livraria_db
      run: |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py test library.tests



